### PR TITLE
Fix fetchChatCmds map race condition

### LINKED ISSUE #15: Race Condition with the chatFetchCmds Map
Multiple goroutines are spun up by StartChatFetch (go monitorAndRestartChatFetch), and all of them compete for access with the chatFetchCmds map, leading to concurrent access panics.

The issue is rare, but can prevent the server from starting.

### Steps To Reproduce
- Add an appreciable number of URLs to fetch from.
- Repeatedly restart the server.
- There is a small chance for a concurrent access panic (difficult to reproduce)

### Potential Fix
Quick fix is to replace the standard map with a sync.map which supports concurrent access.

The chat fetch process also might be able to be refactored to prevent the necessity of this in the first place.

### PR DESCRIPTION
**Pull request by jdavasligil**
fixes #15

The solution just changes the map to a sync.Map for concurrent access safety.

### CODE REVIEW

File: src/backend/routes/chat.go [hunk 1]
```diff
@@ -23,7 +24,7 @@ import (
 // Initialize a Redis client as a global variable.
 var redisClient *redis.Client
 var ctx = context.Background()
-var chatFetchCmds = make(map[string]*exec.Cmd)
+var chatFetchCmds sync.Map // [string]*exec.Cmd
```
Comment (ConnorDY) [inline src/backend/routes/chat.go:27]: Nitpick: remove commented out code. It's in the Git history if we need it.
```suggestion
var chatFetchCmds sync.Map
```

**Review by ConnorDY — APPROVED** [review]
